#!/bin/bash

# http://tldp.org/LDP/abs/html/sample-bashrc.html
# Swap 2 filenames around, if they exist (from Uzi's bashrc).

local TMPFILE=tmp.$$

    [ $# -ne 2 ] && echo "swap: 2 arguments needed" && exit 1
    [ ! -e $1 ] && echo "swap: $1 does not exist" && exit 1
    [ ! -e $2 ] && echo "swap: $2 does not exist" && exit 1

    mv "$1" $TMPFILE
    mv "$2" "$1"
    mv $TMPFILE "$2"