#!/bin/bash

url=$1
file=${url#openlocalfile*//}
path=`echo $file | cut -d? -f 1`
line=`echo $file | cut -d? -f 2`
column=`echo $line | cut -d: -f 2`
line=`echo $line | cut -d: -f 1`
subl $path:$line:$column
