#!/bin/sh

if [ $USER != 'root' ]; then
	if [ -f $1 ]; then
		if [ ! -w $1 ]; then
			echo "This file is not writable !"
			read smthg
#			. /var/lib/christophe-hurpeau/ch-common.lib
#			args=$*
#			editWithSudo= $(yesOrNo "This file is not writable. Do you want edit it with sudo ?" 'y')
#			if [ editWithSudo = 'y' ]; then
#				sudo /usr/bin/nano $args
#				exit $?
#			fi
		fi
	fi
fi

/bin/nano $*
